# Taps
tap 'nicoverbruggen/homebrew-cask'
tap 'stripe/stripe-cli'
tap 'stripe/stripe-mock'

# Binaries
brew 'bash' # Latest Bash version
brew 'coreutils' # Those that come with macOS are outdated
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'stripe/stripe-cli/stripe'
brew 'stripe/stripe-mock/stripe-mock'
brew 'svn' # Needed to install fonts
brew 'wget'

# Spatie Medialibrary
brew 'jpegoptim'
brew 'optipng'
brew 'pngquant'
brew 'svgo'
brew 'gifsicle'

# Development
brew 'awscli'
brew 'aws-cdk'
brew 'cfn-lint' # Cloudformation linter
brew 'go'
brew 'imagemagick'
brew 'ghostscript'
brew 'localstack'
brew 'nvm'
brew 'rust'
brew 'terraform'
brew 'typescript'
brew 'yarn'
brew 'zsh-autosuggestions'

# Apps
cask '1password'
cask 'burn'
cask 'caffeine'
cask 'clamxav'
cask 'balenaetcher'
cask 'balsamiq-wireframes'
cask 'bbedit'
cask 'brave-browser'
cask 'dbngin'
cask 'dbschema'
cask 'discord'
cask 'docker'
cask 'drawio'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'gpg-suite'
cask 'helo'
cask 'iconjar'
cask 'imageoptim'
cask 'insomnia'
cask 'invoker'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'kindle'
cask 'kiro'
cask 'kiro-cli'
cask 'macdown'
cask 'microsoft-edge'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'mysqlworkbench'
cask 'netspot'
cask 'nosql-workbench'
cask 'notion'
cask 'obsidian'
cask 'pastebot'
cask 'pgadmin4'
cask 'postman'
cask 'proton-mail'
cask 'raspberry-pi-imager'
cask 'remote-desktop-manager-free'
cask 'screaming-frog-seo-spider'
cask 'signal'
cask 'sizzy'
cask 'slack'
cask 'tableplus'
cask 'telegram-desktop'
cask 'tinkerwell'
cask 'toggl-track'
cask 'tower'
cask 'transmit'
cask 'tunnelbear'
cask 'tuple'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'

# Quicklook
cask 'betterzip'
cask 'suspicious-package'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'

# Mac App Store
mas 'Alfred', id: 405843582
mas 'Bear - Markdown Notes', id: 1091189122
mas 'Contrast', id: 1254981365
mas 'DaisyDisk', id: 411643860
mas 'Giphy Capture', id: 668208984
mas 'IA Writer', id: 775737590
mas 'Keynote', id: 409183694
mas 'Keka', id: 470158793
mas 'LanScan', id: 472226235
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pluralsight', id: 431748264
mas 'RDM - Redis Desktop Manager', id: 1475905948
mas 'SiteSucker', id: 442168834
mas 'Speedtest', id: 1153157709
mas 'Synalyze It! Pro', id: 475193367
mas 'Tag Editor Free', id: 984278082
mas 'The Unarchiver', id: 425424353
mas 'Xcode', id: 497799835
