#!/bin/bash

echo "Setting up your Mac..."

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin


# Install oh-my-zsh
echo '--=========================================================--'
echo '--= Install oh-my-zsh                                     =--'
echo '--=========================================================--'

rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# install plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions


# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim


# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

# Check for Homebrew and install if we don't have it

echo '--=========================================================--'
echo '--= Install homebrew                                      =--'
echo '--=========================================================--'
echo install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Update Homebrew recipes
brew update

echo '--=========================================================--'
echo '--= Install php                                           =--'
echo '--=========================================================--'
brew tap shivammathur/php
brew install shivammathur/php/php@8.4
brew link --overwrite --force php@8.4

# Install all our dependencies with bundle (See Brewfile)
brew bundle --file $HOME/.dotfiles/shell/Brewfile

echo '--=========================================================--'
echo '-- Install composer                                       =--'
echo '--=========================================================--'
brew install composer

echo '--=========================================================--'
echo '--= Install XCode Command line tools                      =--'
echo '--=========================================================--'
xcode-select --install

echo '--=========================================================--'
echo '--= All done!                                             =--'
echo '--=========================================================--'

echo 'Things to do to make the oh-my-posh terminal theme work:'
echo '1. Install a Nerd Font: brew install font-meslo-lg-nerd-font'
echo '2. Set the font in iTerm2 to "MesloLGS Nerd Font"'

echo '--=========================================================--'
echo '-- Some optional tidbits                                  =--'
echo '--=========================================================--'

echo 'Manully install the following:'
echo 'Adobe Creative Cloud'
echo 'Rosetta'
echo 'Elgato Stream Deck'
echo 'Sonos'
echo ' '
echo '- Set some sensible macOS X defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '- Install the powerline fonts by running $HOME/.dotfiles/macos/install-fonts.sh'
echo '- Setup the dock with the usual apps by running $HOME/.dotfiles/macos/setup-dock.sh'
echo '- If this is an M1/Mx mac, run $HOME/.dotfiles/installm1'

echo '--=========================================================--'

