#!/bin/bash

echo "Setting up your Mac..."

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin


# Install oh-my-zsh
echo '--=========================================================--'
echo '--= Install oh-my-zsh                                     =--'
echo '--=========================================================--'

rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

# Check for Homebrew and install if we don't have it

echo '--=========================================================--'
echo '--= Install homebrew                                      =--'
echo '--=========================================================--'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Update Homebrew recipes
brew update

echo '--=========================================================--'
echo '--= Install php                                           =--'
echo '--=========================================================--'
brew tap shivammathur/php
brew install shivammathur/php/php@8.0
brew link --overwrite --force php@8.0

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle --file $HOME/.dotfiles/shell/Brewfile

echo '--=========================================================--'
echo '-- Install composer                                       =--'
echo '--=========================================================--'
EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi
php composer-setup.php
rm composer-setup.php
sudo mv composer.phar /usr/local/bin/composer

echo '--=========================================================--'
echo '--= All done!                                             =--'
echo '--=========================================================--'

echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '--=========================================================--'
echo '-- Some optional tidbits                                  =--'
echo '--=========================================================--'

echo 'Manully install the following:'
echo 'Adobe Creative Cloud'
echo 'AWS Schema Conversion Tool'
echo 'Balsamiq Mockups 3'
echo 'Camtasia 2019'
echo 'Doodly'
echo 'Rosetta'
echo 'Elgato Stream Deck'
echo 'Sizzy'
echo 'Sonos'
echo 'Stripe-mock'
echo 'Teams'
echo 'Vemto'
echo ' '
echo '- Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '- Set some sensible macOS X defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '- Install the powerline fonts by running $HOME/.dotfiles/macos/install-fonts.sh'
echo '- Setup the dock with the usual apps by running $HOME/.dotfiles/macos/setup-dock.sh'
echo '- If this is an M1/Mx mac, run $HOME/.dotfiles/installm1'

echo '--=========================================================--'

